import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Git-ignored local worktrees can contain independent dependency trees.
    ".worktrees/**",
    // Disposable output generated by `supabase start`; never application source.
    "supabase/.temp/**",
    ".playwright-cli/**",
    // Vendored third-party build artifacts are validated through package-resolution tests.
    "vendor/**",
  ]),
]);

export default eslintConfig;
