// Generated by `npm run db:types` from the designated Supabase project.
// Do not edit manually; update and apply a migration, then regenerate this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_events: {
        Row: {
          action: string
          actor_type: string
          actor_user_id: string | null
          branch_id: string | null
          category: string
          correlation_id: string | null
          entity_id: string | null
          entity_type: string
          id: string
          metadata: Json
          occurred_at: string
          organization_id: string
          patient_id: string | null
          request_id: string | null
          result: string
        }
        Insert: {
          action: string
          actor_type: string
          actor_user_id?: string | null
          branch_id?: string | null
          category: string
          correlation_id?: string | null
          entity_id?: string | null
          entity_type: string
          id?: string
          metadata?: Json
          occurred_at?: string
          organization_id: string
          patient_id?: string | null
          request_id?: string | null
          result: string
        }
        Update: {
          action?: string
          actor_type?: string
          actor_user_id?: string | null
          branch_id?: string | null
          category?: string
          correlation_id?: string | null
          entity_id?: string | null
          entity_type?: string
          id?: string
          metadata?: Json
          occurred_at?: string
          organization_id?: string
          patient_id?: string | null
          request_id?: string | null
          result?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_organization_branch_fk"
            columns: ["organization_id", "branch_id"]
            isOneToOne: false
            referencedRelation: "branches"
            referencedColumns: ["organization_id", "id"]
          },
          {
            foreignKeyName: "audit_events_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_events_organization_patient_fk"
            columns: ["organization_id", "patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["organization_id", "id"]
          },
        ]
      }
      branch_memberships: {
        Row: {
          access_status: string
          branch_id: string
          created_at: string
          granted_at: string
          id: string
          organization_id: string
          organization_member_id: string
          revoked_at: string | null
          updated_at: string
        }
        Insert: {
          access_status?: string
          branch_id: string
          created_at?: string
          granted_at?: string
          id?: string
          organization_id: string
          organization_member_id: string
          revoked_at?: string | null
          updated_at?: string
        }
        Update: {
          access_status?: string
          branch_id?: string
          created_at?: string
          granted_at?: string
          id?: string
          organization_id?: string
          organization_member_id?: string
          revoked_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "branch_memberships_organization_branch_fk"
            columns: ["organization_id", "branch_id"]
            isOneToOne: false
            referencedRelation: "branches"
            referencedColumns: ["organization_id", "id"]
          },
          {
            foreignKeyName: "branch_memberships_organization_member_fk"
            columns: ["organization_id", "organization_member_id"]
            isOneToOne: false
            referencedRelation: "organization_members"
            referencedColumns: ["organization_id", "id"]
          },
        ]
      }
      branches: {
        Row: {
          address_line1: string
          address_line2: string | null
          archived_at: string | null
          city: string
          code: string
          country_code: string
          created_at: string
          email: string | null
          id: string
          latitude: number | null
          longitude: number | null
          name: string
          organization_id: string
          phone: string | null
          postal_code: string | null
          province: string
          slug: string
          status: string
          timezone: string
          updated_at: string
          website_visible: boolean
        }
        Insert: {
          address_line1: string
          address_line2?: string | null
          archived_at?: string | null
          city: string
          code: string
          country_code?: string
          created_at?: string
          email?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
          organization_id: string
          phone?: string | null
          postal_code?: string | null
          province: string
          slug: string
          status?: string
          timezone?: string
          updated_at?: string
          website_visible?: boolean
        }
        Update: {
          address_line1?: string
          address_line2?: string | null
          archived_at?: string | null
          city?: string
          code?: string
          country_code?: string
          created_at?: string
          email?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
          organization_id?: string
          phone?: string | null
          postal_code?: string | null
          province?: string
          slug?: string
          status?: string
          timezone?: string
          updated_at?: string
          website_visible?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "branches_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      member_roles: {
        Row: {
          assigned_at: string
          assigned_by: string | null
          branch_id: string | null
          id: string
          organization_id: string
          organization_member_id: string
          role_id: string
        }
        Insert: {
          assigned_at?: string
          assigned_by?: string | null
          branch_id?: string | null
          id?: string
          organization_id: string
          organization_member_id: string
          role_id: string
        }
        Update: {
          assigned_at?: string
          assigned_by?: string | null
          branch_id?: string | null
          id?: string
          organization_id?: string
          organization_member_id?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "member_roles_branch_membership_fk"
            columns: ["branch_id", "organization_member_id"]
            isOneToOne: false
            referencedRelation: "branch_memberships"
            referencedColumns: ["branch_id", "organization_member_id"]
          },
          {
            foreignKeyName: "member_roles_organization_branch_fk"
            columns: ["organization_id", "branch_id"]
            isOneToOne: false
            referencedRelation: "branches"
            referencedColumns: ["organization_id", "id"]
          },
          {
            foreignKeyName: "member_roles_organization_member_fk"
            columns: ["organization_id", "organization_member_id"]
            isOneToOne: false
            referencedRelation: "organization_members"
            referencedColumns: ["organization_id", "id"]
          },
          {
            foreignKeyName: "member_roles_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_members: {
        Row: {
          created_at: string
          id: string
          joined_at: string | null
          membership_status: string
          organization_id: string
          suspended_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          joined_at?: string | null
          membership_status?: string | null
          organization_id: string
          suspended_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          joined_at?: string | null
          membership_status?: string | null
          organization_id?: string
          suspended_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          archived_at: string | null
          business_name: string
          country_code: string
          created_at: string
          default_currency: string
          default_timezone: string
          id: string
          legal_name: string
          slug: string
          status: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          business_name: string
          country_code?: string
          created_at?: string
          default_currency?: string
          default_timezone?: string
          id?: string
          legal_name: string
          slug: string
          status?: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          business_name?: string
          country_code?: string
          created_at?: string
          default_currency?: string
          default_timezone?: string
          id?: string
          legal_name?: string
          slug?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      patient_contacts: {
        Row: {
          archived_at: string | null
          contact_type: string
          created_at: string
          id: string
          is_primary: boolean
          label: string | null
          normalized_value: string | null
          organization_id: string
          patient_id: string
          status: string
          updated_at: string
          value: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          contact_type: string
          created_at?: string
          id?: string
          is_primary?: boolean
          label?: string | null
          normalized_value?: string | null
          organization_id: string
          patient_id: string
          status?: string
          updated_at?: string
          value: string
          version?: number
        }
        Update: {
          archived_at?: string | null
          contact_type?: string
          created_at?: string
          id?: string
          is_primary?: boolean
          label?: string | null
          normalized_value?: string | null
          organization_id?: string
          patient_id?: string
          status?: string
          updated_at?: string
          value?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "patient_contacts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_contacts_organization_patient_fk"
            columns: ["organization_id", "patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["organization_id", "id"]
          },
        ]
      }
      patient_relationships: {
        Row: {
          archived_at: string | null
          can_consent: boolean
          can_receive_communications: boolean
          created_at: string
          external_contact_name: string | null
          external_email: string | null
          external_mobile: string | null
          id: string
          is_legal_guardian: boolean
          organization_id: string
          patient_id: string
          related_patient_id: string | null
          relationship_type: string
          status: string
          updated_at: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          can_consent?: boolean
          can_receive_communications?: boolean
          created_at?: string
          external_contact_name?: string | null
          external_email?: string | null
          external_mobile?: string | null
          id?: string
          is_legal_guardian?: boolean
          organization_id: string
          patient_id: string
          related_patient_id?: string | null
          relationship_type: string
          status?: string
          updated_at?: string
          version?: number
        }
        Update: {
          archived_at?: string | null
          can_consent?: boolean
          can_receive_communications?: boolean
          created_at?: string
          external_contact_name?: string | null
          external_email?: string | null
          external_mobile?: string | null
          id?: string
          is_legal_guardian?: boolean
          organization_id?: string
          patient_id?: string
          related_patient_id?: string | null
          relationship_type?: string
          status?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "patient_relationships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_relationships_organization_patient_fk"
            columns: ["organization_id", "patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["organization_id", "id"]
          },
          {
            foreignKeyName: "patient_relationships_organization_related_patient_fk"
            columns: ["organization_id", "related_patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["organization_id", "id"]
          },
        ]
      }
      patients: {
        Row: {
          address_line1: string | null
          address_line2: string | null
          archived_at: string | null
          birth_date: string
          city: string | null
          created_at: string
          created_by_user_id: string | null
          first_name: string
          id: string
          last_name: string
          middle_name: string | null
          normalized_first_name: string | null
          normalized_full_name: string | null
          normalized_last_name: string | null
          normalized_middle_name: string | null
          organization_id: string
          patient_number: string
          postal_code: string | null
          preferred_branch_id: string | null
          preferred_name: string | null
          province: string | null
          sex_at_registration: string | null
          status: string
          suffix: string | null
          updated_at: string
          version: number
        }
        Insert: {
          address_line1?: string | null
          address_line2?: string | null
          archived_at?: string | null
          birth_date: string
          city?: string | null
          created_at?: string
          created_by_user_id?: string | null
          first_name: string
          id?: string
          last_name: string
          middle_name?: string | null
          normalized_first_name?: string | null
          normalized_full_name?: string | null
          normalized_last_name?: string | null
          normalized_middle_name?: string | null
          organization_id: string
          patient_number: string
          postal_code?: string | null
          preferred_branch_id?: string | null
          preferred_name?: string | null
          province?: string | null
          sex_at_registration?: string | null
          status?: string
          suffix?: string | null
          updated_at?: string
          version?: number
        }
        Update: {
          address_line1?: string | null
          address_line2?: string | null
          archived_at?: string | null
          birth_date?: string
          city?: string | null
          created_at?: string
          created_by_user_id?: string | null
          first_name?: string
          id?: string
          last_name?: string
          middle_name?: string | null
          normalized_first_name?: string | null
          normalized_full_name?: string | null
          normalized_last_name?: string | null
          normalized_middle_name?: string | null
          organization_id?: string
          patient_number?: string
          postal_code?: string | null
          preferred_branch_id?: string | null
          preferred_name?: string | null
          province?: string | null
          sex_at_registration?: string | null
          status?: string
          suffix?: string | null
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "patients_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patients_organization_preferred_branch_fk"
            columns: ["organization_id", "preferred_branch_id"]
            isOneToOne: false
            referencedRelation: "branches"
            referencedColumns: ["organization_id", "id"]
          },
        ]
      }
      permissions: {
        Row: {
          code: string
          created_at: string
          description: string
          id: string
        }
        Insert: {
          code: string
          created_at?: string
          description: string
          id?: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string
          id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_object_key: string | null
          created_at: string
          display_name: string
          first_name: string
          last_name: string
          mobile: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          avatar_object_key?: string | null
          created_at?: string
          display_name: string
          first_name: string
          last_name: string
          mobile?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          avatar_object_key?: string | null
          created_at?: string
          display_name?: string
          first_name?: string
          last_name?: string
          mobile?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      role_permissions: {
        Row: {
          created_at: string
          permission_id: string
          role_id: string
        }
        Insert: {
          created_at?: string
          permission_id: string
          role_id: string
        }
        Update: {
          created_at?: string
          permission_id?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_permissions_permission_id_fkey"
            columns: ["permission_id"]
            isOneToOne: false
            referencedRelation: "permissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "role_permissions_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          code: string
          created_at: string
          id: string
          is_system: boolean
          name: string
          organization_id: string | null
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_system?: boolean
          name: string
          organization_id?: string | null
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_system?: boolean
          name?: string
          organization_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "roles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_workforce_invitation: {
        Args: {
          p_auth_user_id: string
          p_first_name: string
          p_last_name: string
        }
        Returns: string
      }
      archive_branch: { Args: { target_branch_id: string }; Returns: string }
      archive_patient: {
        Args: {
          p_acting_branch_id: string
          p_expected_version: number
          p_patient_id: string
        }
        Returns: {
          patient_id: string
          version: number
        }[]
      }
      archive_patient_contact: {
        Args: {
          p_acting_branch_id: string
          p_contact_id: string
          p_expected_version: number
          p_patient_id: string
        }
        Returns: {
          contact_id: string
          version: number
        }[]
      }
      archive_patient_relationship: {
        Args: {
          p_acting_branch_id: string
          p_expected_version: number
          p_patient_id: string
          p_relationship_id: string
        }
        Returns: {
          relationship_id: string
          version: number
        }[]
      }
      create_branch: {
        Args: {
          branch_address_line1: string
          branch_address_line2?: string
          branch_city: string
          branch_code: string
          branch_country_code?: string
          branch_email?: string
          branch_latitude?: number
          branch_longitude?: number
          branch_name: string
          branch_phone?: string
          branch_postal_code?: string
          branch_province: string
          branch_slug: string
          branch_timezone?: string
          branch_website_visible?: boolean
          target_organization_id: string
        }
        Returns: string
      }
      create_patient: {
        Args: {
          p_acting_branch_id: string
          p_address_line1: string | null
          p_address_line2: string | null
          p_birth_date: string
          p_city: string | null
          p_duplicate_confirmed: boolean
          p_first_name: string
          p_initial_email: string | null
          p_initial_mobile: string | null
          p_last_name: string
          p_middle_name: string | null
          p_postal_code: string | null
          p_preferred_branch_id: string | null
          p_preferred_name: string | null
          p_province: string | null
          p_sex_at_registration: string | null
          p_suffix: string | null
        }
        Returns: {
          patient_id: string
          version: number
        }[]
      }
      create_patient_contact: {
        Args: {
          p_acting_branch_id: string
          p_contact_type: string
          p_duplicate_confirmed: boolean
          p_is_primary: boolean
          p_label: string | null
          p_patient_id: string
          p_value: string
        }
        Returns: {
          contact_id: string
          version: number
        }[]
      }
      create_patient_relationship: {
        Args: {
          p_acting_branch_id: string
          p_can_consent: boolean
          p_can_receive_communications: boolean
          p_external_contact_name: string | null
          p_external_email: string | null
          p_external_mobile: string | null
          p_is_legal_guardian: boolean
          p_patient_id: string
          p_related_patient_id: string | null
          p_relationship_type: string
        }
        Returns: {
          relationship_id: string
          version: number
        }[]
      }
      fail_workforce_invitation: {
        Args: { p_invitation_id: string }
        Returns: undefined
      }
      finalize_workforce_invitation: {
        Args: {
          p_actor_user_id: string
          p_auth_user_id: string
          p_invitation_id: string
        }
        Returns: string
      }
      find_duplicate_candidates: {
        Args: {
          p_acting_branch_id: string
          p_birth_date: string
          p_first_name: string
          p_initial_email?: string
          p_initial_mobile?: string
          p_last_name: string
        }
        Returns: Json
      }
      get_patient_detail: {
        Args: { p_acting_branch_id: string; p_patient_id: string }
        Returns: Json
      }
      get_workforce_invitation_summary: {
        Args: { p_auth_user_id: string }
        Returns: Json
      }
      list_workforce_invitation_options: {
        Args: { p_actor_user_id: string }
        Returns: Json
      }
      prepare_first_owner_invitation: {
        Args: {
          p_email: string
          p_invitation_id: string
          p_organization_id: string
        }
        Returns: string
      }
      prepare_workforce_invitation: {
        Args: {
          p_actor_user_id: string
          p_branch_id?: string
          p_email: string
          p_invitation_id: string
          p_organization_id: string
          p_role_id: string
        }
        Returns: string
      }
      reactivate_patient: {
        Args: {
          p_acting_branch_id: string
          p_expected_version: number
          p_patient_id: string
        }
        Returns: {
          patient_id: string
          version: number
        }[]
      }
      record_mfa_enrollment: { Args: { p_factor_id: string }; Returns: number }
      revoke_workforce_invitation: {
        Args: { p_actor_user_id: string; p_invitation_id: string }
        Returns: boolean
      }
      search_patients: {
        Args: {
          p_acting_branch_id: string
          p_birth_date?: string | null
          p_page?: number
          p_page_size?: number
          p_query?: string | null
          p_sort?: string
          p_status?: string | null
        }
        Returns: Json
      }
      set_branch_membership: {
        Args: {
          target_access_status: string
          target_branch_id: string
          target_organization_member_id: string
        }
        Returns: string
      }
      set_member_role: {
        Args: {
          grant_role: boolean
          target_branch_id: string
          target_organization_member_id: string
          target_role_id: string
        }
        Returns: string
      }
      set_role_permission: {
        Args: {
          grant_permission: boolean
          target_permission_code: string
          target_role_id: string
        }
        Returns: string
      }
      update_branch: {
        Args: {
          branch_address_line1: string
          branch_address_line2?: string
          branch_city: string
          branch_email?: string
          branch_name: string
          branch_phone?: string
          branch_postal_code?: string
          branch_province: string
          branch_timezone?: string
          branch_website_visible?: boolean
          target_branch_id: string
        }
        Returns: string
      }
      update_organization_member_status: {
        Args: {
          target_membership_status: string
          target_organization_member_id: string
        }
        Returns: string
      }
      update_patient: {
        Args: {
          p_acting_branch_id: string
          p_duplicate_confirmed: boolean
          p_expected_version: number
          p_patch: Json
          p_patient_id: string
        }
        Returns: {
          patient_id: string
          version: number
        }[]
      }
      update_patient_contact: {
        Args: {
          p_acting_branch_id: string
          p_contact_id: string
          p_contact_type: string
          p_duplicate_confirmed: boolean
          p_expected_version: number
          p_is_primary: boolean
          p_label: string | null
          p_patient_id: string
          p_value: string
        }
        Returns: {
          contact_id: string
          version: number
        }[]
      }
      update_patient_relationship: {
        Args: {
          p_acting_branch_id: string
          p_can_consent: boolean
          p_can_receive_communications: boolean
          p_expected_version: number
          p_external_contact_name: string | null
          p_external_email: string | null
          p_external_mobile: string | null
          p_is_legal_guardian: boolean
          p_patient_id: string
          p_related_patient_id: string | null
          p_relationship_id: string
          p_relationship_type: string
        }
        Returns: {
          relationship_id: string
          version: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
