"use client";

import * as React from "react";
import { Download } from "lucide-react";

import { recordClinicalExportAction } from "@/app/(emr)/patients/[patientId]/odontogram-interchange-actions";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  MAX_EXPORT_SVG_DIMENSION,
  clampExportScale,
  sanitizeChartExportSvg,
} from "@/lib/odontogram/clinical-export";
import type {
  ClinicalExportFormat,
  ClinicalExportScope,
} from "@/lib/odontogram/interchange/schema";

/**
 * The export menu.
 *
 * Every entry registers the export server-side FIRST and only then produces
 * anything to download. That ordering is the point: an export of a patient's
 * record is an accountable act, and the audit trail must not depend on the
 * browser finishing what it started.
 *
 * The two document formats are generated by the server from authorized
 * projections. The three rendered formats are produced here from the closed
 * renderer's own SVG, sanitized and dimension-clamped before it leaves the
 * page - never from fork state, and never carrying a media URL.
 */

const EXPORTS: ReadonlyArray<{ format: ClinicalExportFormat; label: string }> = Object.freeze([
  { format: "FHIR_R4_BUNDLE", label: "FHIR R4 Bundle" },
  { format: "EMR_JSON_V1", label: "Dental EMR JSON" },
  { format: "SVG", label: "Chart image (SVG)" },
  { format: "PNG", label: "Chart image (PNG)" },
  { format: "PDF", label: "Print or save as PDF" },
]);

/** The formats whose bytes this page produces from the mounted renderer. */
const renderedFormats: ReadonlySet<ClinicalExportFormat> = new Set(["SVG", "PNG"]);

function saveLocally(filename: string, contentType: string, body: BlobPart): void {
  const url = URL.createObjectURL(new Blob([body], { type: contentType }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.rel = "noopener";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

async function rasterize(svg: string): Promise<Blob | null> {
  const scale = clampExportScale(2);
  const canvas = document.createElement("canvas");
  const context = canvas.getContext?.("2d");
  if (!context) return null;

  const width = Math.min(
    Number.parseInt(/\bwidth="(\d+)"/.exec(svg)?.[1] ?? "", 10) || MAX_EXPORT_SVG_DIMENSION,
    MAX_EXPORT_SVG_DIMENSION,
  );
  const height = Math.min(
    Number.parseInt(/\bheight="(\d+)"/.exec(svg)?.[1] ?? "", 10) || MAX_EXPORT_SVG_DIMENSION,
    MAX_EXPORT_SVG_DIMENSION,
  );
  canvas.width = Math.min(width * scale, MAX_EXPORT_SVG_DIMENSION);
  canvas.height = Math.min(height * scale, MAX_EXPORT_SVG_DIMENSION);

  const source = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" }));
  try {
    const image = new Image();
    await new Promise<void>((resolve, reject) => {
      image.addEventListener("load", () => resolve());
      image.addEventListener("error", () => reject(new Error("render failed")));
      image.src = source;
    });
    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    return await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"));
  } finally {
    URL.revokeObjectURL(source);
  }
}

export type ClinicalExportMenuProps = {
  patientId: string;
  branchId: string;
  scope?: ClinicalExportScope;
  /** Serializes the mounted closed renderer's SVG. Never fork state. */
  getChartSvg?: () => string | null;
  /** Print surface for the PDF path. Defaults to the browser's own. */
  onPrint?: () => void;
};

export function ClinicalExportMenu({
  patientId,
  branchId,
  scope = "CHART_AND_PROGRESS",
  getChartSvg,
  onPrint,
}: ClinicalExportMenuProps): React.ReactElement {
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  async function exportAs(format: ClinicalExportFormat) {
    setBusy(true);
    setError(null);
    try {
      // REVIEW ROUND 1, item 1. The picture is produced BEFORE the export is
      // registered. Registering first would write an export record and an audit
      // event for a download that then never happened, and an audit trail that
      // records intentions rather than outcomes is not an audit trail.
      let picture: string | Blob | null = null;

      if (format === "SVG" || format === "PNG") {
        const svg = sanitizeChartExportSvg(getChartSvg?.() ?? "");
        if (svg === "") {
          setError("The chart is not on screen, so there is nothing to export as an image.");
          return;
        }
        if (format === "PNG") {
          picture = await rasterize(svg);
          if (picture === null) {
            setError("The chart image could not be rendered. Export the SVG instead.");
            return;
          }
        } else {
          picture = svg;
        }
      }

      const registered = await recordClinicalExportAction({
        branchId,
        patientId,
        format,
        scope,
        idempotencyKey: crypto.randomUUID(),
      });

      if (!registered.ok) {
        setError(
          registered.code === "NOT_AUTHORIZED"
            ? "Your clinical access or selected branch changed. Nothing was exported; refresh before retrying."
            : "The export could not be prepared. Try again.",
        );
        return;
      }

      // The server generates the two document formats during registration.
      if (registered.body !== null) {
        saveLocally(registered.filename, registered.contentType, registered.body);
        return;
      }

      if (picture !== null) {
        saveLocally(registered.filename, registered.contentType, picture);
        return;
      }

      // Print is the one export whose artifact this page cannot hold: the
      // browser owns the dialog and the paper. Registration is still the last
      // thing before the surface opens.
      //
      // Named explicitly rather than left as a fall-through. Any other format
      // arriving here means the server registered a document export and
      // returned no body, which is a failure - opening a print dialog instead
      // would silently substitute a different artifact for the one asked for.
      if (format === "PDF") {
        (onPrint ?? (() => window.print()))();
        return;
      }

      setError("The export could not be prepared. Try again.");
    } catch {
      setError("The export could not be prepared. Try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex min-w-0 flex-col gap-1">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button type="button" variant="outline" size="sm" className="min-h-11" disabled={busy}>
            <Download aria-hidden="true" /> Export chart
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          {EXPORTS.filter(
            // A chart-image export needs a mounted chart to serialize. Where
            // there is none - the periodontal mode, or a screen that never
            // supplied one - the two rendered formats are not offered at all
            // rather than offered and then refused.
            (option) => renderedFormats.has(option.format) === false || getChartSvg !== undefined,
          ).map((option) => (
            <DropdownMenuItem key={option.format} onSelect={() => void exportAs(option.format)}>
              {option.label}
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
      {error && (
        <p role="alert" className="text-xs text-destructive">
          {error}
        </p>
      )}
    </div>
  );
}
