alter table public.procedure_installment_schedules drop constraint if exists procedure_installment_schedules_organization_id_procedure_case_id_key;
create unique index if not exists procedure_installment_schedules_active_case_key on public.procedure_installment_schedules(organization_id,procedure_case_id) where status='ACTIVE';
create or replace function public.amend_procedure_installment_schedule(p_acting_branch_id uuid,p_schedule_id uuid,p_event_type text,p_items jsonb,p_reason text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_org uuid;v_actor uuid:=(select auth.uid());v_old public.procedure_installment_schedules%rowtype;v_new uuid;v_version integer;
begin
 if p_event_type not in('AMENDED','CANCELLED','COMPLETED') or p_idempotency_key is null or length(p_idempotency_key) not between 1 and 128 or p_idempotency_key<>btrim(p_idempotency_key) or (p_event_type='AMENDED' and (jsonb_typeof(p_items)!='array' or jsonb_array_length(p_items) not between 1 and 120)) then raise invalid_parameter_value using message='invalid input';end if;
 select organization_id into v_org from public.branches where id=p_acting_branch_id and status='active';if v_org is null or v_actor is null or not private.has_billing_permission_at_branch(p_acting_branch_id,'payment.record') then raise insufficient_privilege using message='not authorized';end if;
 select * into v_old from public.procedure_installment_schedules where organization_id=v_org and id=p_schedule_id for update;if not found or v_old.status<>'ACTIVE' then raise exception using errcode='P0001',message='invalid state';end if;
 v_version:=v_old.version+1;
 if p_event_type='AMENDED' then insert into public.procedure_installment_schedules(organization_id,procedure_case_id,version,status,created_by,operation_actor_id,idempotency_key) values(v_org,v_old.procedure_case_id,v_version,'ACTIVE',v_actor,v_actor,p_idempotency_key) returning id into v_new; insert into public.procedure_installment_schedule_items(organization_id,schedule_id,ordinal,due_date,expected_centavos) select v_org,v_new,ord,(x->>'dueDate')::date,(x->>'expectedCentavos')::bigint from jsonb_array_elements(p_items) with ordinality a(x,ord); update public.procedure_installment_schedules set status='CANCELLED' where organization_id=v_org and id=v_old.id; else v_new:=v_old.id; update public.procedure_installment_schedules set status=case when p_event_type='CANCELLED' then 'CANCELLED' else 'COMPLETED' end,version=v_version where organization_id=v_org and id=v_old.id;end if;
 insert into public.procedure_installment_schedule_events(organization_id,schedule_id,event_type,version,reason,actor_id,idempotency_key) values(v_org,v_new,p_event_type,v_version,nullif(btrim(p_reason),''),v_actor,p_idempotency_key);
 return jsonb_build_object('schedule_id',v_new,'status',case when p_event_type='CANCELLED' then 'CANCELLED' when p_event_type='COMPLETED' then 'COMPLETED' else 'ACTIVE' end,'version',v_version);
end $$;revoke all on function public.amend_procedure_installment_schedule(uuid,uuid,text,jsonb,text,text) from public,anon,authenticated,service_role;
