-- O8 repair: serializable per-case expectation schedule operations and append-only lifecycle.
alter table public.procedure_installment_schedules add column if not exists idempotency_key text not null default 'legacy', add column if not exists operation_actor_id uuid references auth.users(id) on delete restrict;
alter table public.procedure_installment_schedules add constraint procedure_installment_schedule_idempotency_key_check check (length(idempotency_key) between 1 and 128 and idempotency_key=btrim(idempotency_key));
create unique index if not exists procedure_installment_schedules_operation_key on public.procedure_installment_schedules(organization_id,operation_actor_id,idempotency_key) where operation_actor_id is not null;
create table public.procedure_installment_schedule_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null, schedule_id uuid not null, event_type text not null, version integer not null, reason text, actor_id uuid not null references auth.users(id), idempotency_key text not null, occurred_at timestamptz not null default statement_timestamp(), unique(organization_id,id), unique(organization_id,schedule_id,version), foreign key(organization_id,schedule_id) references public.procedure_installment_schedules(organization_id,id) on delete restrict, check(event_type in('CREATED','AMENDED','CANCELLED','COMPLETED')), check(version>0),check(length(idempotency_key) between 1 and 128));
alter table public.procedure_installment_schedule_events enable row level security; revoke all on public.procedure_installment_schedule_events from public,anon,authenticated,service_role;
create or replace function public.create_procedure_installment_schedule(p_acting_branch_id uuid,p_procedure_case_id uuid,p_items jsonb,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_org uuid;v_actor uuid:=(select auth.uid());v_id uuid;v_case public.procedure_cases%rowtype;
begin
 if p_idempotency_key is null or length(p_idempotency_key) not between 1 and 128 or p_idempotency_key<>btrim(p_idempotency_key) or jsonb_typeof(p_items)!='array' or jsonb_array_length(p_items) not between 1 and 120 then raise invalid_parameter_value using message='invalid input';end if;
 select organization_id into v_org from public.branches where id=p_acting_branch_id and status='active'; if v_org is null or v_actor is null or not private.has_billing_permission_at_branch(p_acting_branch_id,'payment.record') then raise insufficient_privilege using message='not authorized';end if;
 if exists(select 1 from jsonb_array_elements(p_items) x where jsonb_typeof(x)!='object' or not (x ? 'dueDate' and x ? 'expectedCentavos') or coalesce(x->>'dueDate','') !~ '^\\d{4}-\\d{2}-\\d{2}$' or coalesce(x->>'expectedCentavos','') !~ '^[1-9]\\d*$') then raise invalid_parameter_value using message='invalid input';end if;
 begin perform (x->>'dueDate')::date from jsonb_array_elements(p_items) x; exception when others then raise invalid_parameter_value using message='invalid input'; end;
 perform pg_advisory_xact_lock(hashtextextended(v_org::text||p_procedure_case_id::text,0));
 select id into v_id from public.procedure_installment_schedules where organization_id=v_org and operation_actor_id=v_actor and idempotency_key=p_idempotency_key; if v_id is null then
  select * into v_case from public.procedure_cases where organization_id=v_org and id=p_procedure_case_id for key share; if not found or v_case.status='CANCELLED' then raise insufficient_privilege using message='not authorized';end if;
  if exists(select 1 from public.procedure_installment_schedules where organization_id=v_org and procedure_case_id=p_procedure_case_id and status='ACTIVE') then raise exception using errcode='P0001',message='schedule already exists';end if;
  insert into public.procedure_installment_schedules(organization_id,procedure_case_id,created_by,operation_actor_id,idempotency_key) values(v_org,p_procedure_case_id,v_actor,v_actor,p_idempotency_key) returning id into v_id;
  insert into public.procedure_installment_schedule_items(organization_id,schedule_id,ordinal,due_date,expected_centavos) select v_org,v_id,ord,(x->>'dueDate')::date,(x->>'expectedCentavos')::bigint from jsonb_array_elements(p_items) with ordinality a(x,ord);
  insert into public.procedure_installment_schedule_events(organization_id,schedule_id,event_type,version,actor_id,idempotency_key) values(v_org,v_id,'CREATED',1,v_actor,p_idempotency_key);
 end if;
 return jsonb_build_object('schedule_id',v_id,'procedure_case_id',p_procedure_case_id,'status','ACTIVE','version',1,'items',(select jsonb_agg(jsonb_build_object('ordinal',ordinal,'due_date',due_date,'expected_centavos',expected_centavos::text) order by ordinal) from public.procedure_installment_schedule_items where organization_id=v_org and schedule_id=v_id));
end $$; revoke all on function public.create_procedure_installment_schedule(uuid,uuid,jsonb,text) from public,anon,authenticated,service_role;
