-- Unified Clinical Chart workspace, task 9: the canonical periodontal and
-- peri-implant measurement model.
--
-- Forward-only. The five periodontal tables introduced by 20260828020200 and
-- refined by 20260828020515/020518/020520 are EXTENDED here. No parallel
-- canonical store is created, no applied migration is edited, and no clinical
-- measurement is invented: every new column is nullable with no default, so an
-- examination recorded before this migration stays exactly as readable as it
-- was, and a measurement that was never taken stays absent instead of
-- collapsing into zero or false.
--
-- Six changes:
--
-- 1. Unknown becomes representable. The gingival margin, bleeding on probing,
--    suppuration, and plaque presence carried NOT NULL DEFAULT 0/false, so a
--    site nobody assessed was indistinguishable from a healthy site. They lose
--    the NOT NULL and the default. Derived CAL is a generated column, so an
--    unknown gingival margin now yields an unknown CAL rather than silently
--    reporting the probing depth as the attachment level.
--
-- 2. Surface indices. The plaque table gains the Silness-Loe plaque index and
--    the Loe-Silness gingival index for natural teeth, and the Mombelli
--    modified plaque and modified bleeding indices for peri-implant surfaces.
--    Applicability is enforced, not documented: the natural-tooth family and
--    the peri-implant family may never appear on one surface, and a constraint
--    trigger refuses each family against the wrong context, reading the
--    authoritative implant flag from the tooth row rather than duplicating it.
--
-- 3. Tooth and implant properties. Keratinized gingiva width, gingival
--    thickness, and gingival phenotype apply to teeth and implants alike.
--    Miller recession class, CEJ visibility, and root concavity describe
--    structures an implant does not have and are refused in an implant
--    context. Miller mobility was already refused there.
--
-- 4. Examination risk inputs. Age snapshot, smoking status and cigarettes per
--    day, diabetes status and HbA1c, teeth lost to periodontitis, and
--    radiographic bone loss are the 2018 staging and grading inputs. Every one
--    is bounded; cigarettes per day is accepted only for a current smoker.
--
-- 5. Classification with provenance. The derived classification and the
--    clinician-confirmed classification are stored separately and never
--    overwrite one another. A confirmation must name its confirming user,
--    provider (tenant-safe), and time; a confirmation that departs from the
--    derived result must state a bounded, non-empty reason. Both
--    classifications carry a fingerprint over the canonical measurements, and a
--    constraint trigger refuses a fingerprint that is not the true digest, so
--    the provenance cannot be forged or back-dated.
--
-- 6. Amendment lineage. A superseding examination now records why. The reason
--    is bounded and non-empty, is accepted only with a predecessor, and is
--    MANDATORY once the amendment reaches FINAL — a DRAFT amendment may still
--    be autosaved without one, but the authoritative record that replaces
--    finalized clinical history can never exist unexplained. A partial unique
--    index refuses a second successor so the chain cannot fork.
--
-- FINAL immutability needs no new trigger: private.protect_finalized_perio_
-- examination and private.reject_finalized_perio_child_mutation reject the
-- whole row, carry no column list, and therefore already cover every column
-- added here. The suite proves that for the new columns rather than assuming
-- it.
--
-- This migration grants nothing. 20260901010201 owns the boundary assertion and
-- also grants nothing, because task 9 adds no browser-callable function.

-- ---------------------------------------------------------------------------
-- 1. Unknown is representable
-- ---------------------------------------------------------------------------

alter table public.periodontal_site_measurements
  alter column gingival_margin_mm drop default,
  alter column gingival_margin_mm drop not null,
  alter column bleeding_on_probing drop default,
  alter column bleeding_on_probing drop not null,
  alter column suppuration drop default,
  alter column suppuration drop not null;

comment on column public.periodontal_site_measurements.gingival_margin_mm is
  'Signed gingival margin in millimetres, positive = recession. NULL means the margin was not recorded; derived cal_mm is then NULL too, because an unknown margin makes the attachment level unknown, not equal to the probing depth.';
comment on column public.periodontal_site_measurements.cal_mm is
  'Derived clinical attachment level: probing_depth_mm + gingival_margin_mm, generated by the database. NULL whenever the gingival margin is unknown.';
comment on column public.periodontal_site_measurements.bleeding_on_probing is
  'NULL means the site was not assessed for bleeding. False means assessed and not bleeding.';
comment on column public.periodontal_site_measurements.suppuration is
  'NULL means the site was not assessed for suppuration. False means assessed and absent.';

alter table public.periodontal_plaque_measurements
  alter column plaque_present drop default,
  alter column plaque_present drop not null;

comment on column public.periodontal_plaque_measurements.plaque_present is
  'O''Leary plaque presence. NULL means the surface was not assessed. False means assessed and plaque free.';

-- ---------------------------------------------------------------------------
-- 2. Surface indices with natural-tooth and peri-implant applicability
-- ---------------------------------------------------------------------------

alter table public.periodontal_plaque_measurements
  add column plaque_index smallint,
  add column gingival_index smallint,
  add column modified_plaque_index smallint,
  add column modified_bleeding_index smallint;

alter table public.periodontal_plaque_measurements
  add constraint perio_plaque_plaque_index_range
    check (plaque_index is null or plaque_index between 0 and 3),
  add constraint perio_plaque_gingival_index_range
    check (gingival_index is null or gingival_index between 0 and 3),
  add constraint perio_plaque_modified_plaque_index_range
    check (modified_plaque_index is null or modified_plaque_index between 0 and 3),
  add constraint perio_plaque_modified_bleeding_index_range
    check (modified_bleeding_index is null or modified_bleeding_index between 0 and 3),
  -- The Silness-Loe / Loe-Silness pair scores a natural dentition; the Mombelli
  -- modified pair scores a peri-implant sulcus. One surface is one or the
  -- other, never both.
  add constraint perio_plaque_index_family_check check (
    pg_catalog.num_nonnulls(plaque_index, gingival_index) = 0
    or pg_catalog.num_nonnulls(modified_plaque_index, modified_bleeding_index) = 0
  );

comment on column public.periodontal_plaque_measurements.plaque_index is
  'Silness-Loe Plaque Index 0-3 for a natural-tooth surface. NULL when not scored. Refused on a peri-implant surface.';
comment on column public.periodontal_plaque_measurements.gingival_index is
  'Loe-Silness Gingival Index 0-3 for a natural-tooth surface. NULL when not scored. Refused on a peri-implant surface.';
comment on column public.periodontal_plaque_measurements.modified_plaque_index is
  'Mombelli modified Plaque Index 0-3 for a peri-implant surface. NULL when not scored. Refused on a natural tooth.';
comment on column public.periodontal_plaque_measurements.modified_bleeding_index is
  'Mombelli modified Bleeding Index 0-3 for a peri-implant surface. NULL when not scored. Refused on a natural tooth.';

comment on table public.periodontal_plaque_measurements is
  'Per-tooth, four-surface periodontal surface record: O''Leary plaque presence plus the natural-tooth (Silness-Loe / Loe-Silness) or peri-implant (Mombelli modified) index family. The implant context is not duplicated here; it is read from the tooth row, which is the single source of truth.';

-- ---------------------------------------------------------------------------
-- 3. Tooth and implant properties
-- ---------------------------------------------------------------------------

alter table public.periodontal_tooth_measurements
  add column keratinized_gingiva_mm smallint,
  add column gingival_thickness_mm numeric(3,1),
  add column gingival_phenotype text,
  add column miller_recession_class text,
  add column cej_visible boolean,
  add column root_concavity boolean;

alter table public.periodontal_tooth_measurements
  add constraint perio_tooth_keratinized_gingiva_range
    check (keratinized_gingiva_mm is null or keratinized_gingiva_mm between 0 and 15),
  add constraint perio_tooth_gingival_thickness_range
    check (gingival_thickness_mm is null or gingival_thickness_mm between 0.1 and 9.9),
  add constraint perio_tooth_gingival_phenotype_check
    check (gingival_phenotype is null or gingival_phenotype in ('THIN', 'THICK')),
  add constraint perio_tooth_miller_recession_class_check
    check (miller_recession_class is null or miller_recession_class in ('I', 'II', 'III', 'IV')),
  -- An implant has no root, no cemento-enamel junction, and no interdental
  -- attachment to classify Miller recession against. Keratinized mucosa width,
  -- thickness, and phenotype remain valid peri-implant measurements.
  add constraint perio_tooth_implant_property_check check (
    not implant_context
    or (miller_recession_class is null and cej_visible is null and root_concavity is null)
  );

comment on column public.periodontal_tooth_measurements.keratinized_gingiva_mm is
  'Apico-coronal width of keratinized gingiva or peri-implant keratinized mucosa in millimetres, 0-15. NULL when not measured.';
comment on column public.periodontal_tooth_measurements.gingival_thickness_mm is
  'Bucco-lingual gingival or mucosal thickness in millimetres, 0.1-9.9. NULL when not measured; a measured thickness is never zero.';
comment on column public.periodontal_tooth_measurements.gingival_phenotype is
  'THIN or THICK periodontal phenotype. NULL when not assessed.';
comment on column public.periodontal_tooth_measurements.miller_recession_class is
  'Miller I-IV gingival recession classification. Natural teeth only. NULL when there is no recession to classify or it was not assessed.';
comment on column public.periodontal_tooth_measurements.cej_visible is
  'Whether the cemento-enamel junction is clinically visible. Natural teeth only. NULL when not assessed.';
comment on column public.periodontal_tooth_measurements.root_concavity is
  'Whether a root concavity complicates instrumentation. Natural teeth only. NULL when not assessed.';

-- ---------------------------------------------------------------------------
-- 4. Examination risk inputs
-- ---------------------------------------------------------------------------

alter table public.periodontal_examinations
  add column age_years_snapshot smallint,
  add column smoking_status text,
  add column cigarettes_per_day smallint,
  add column diabetes_status text,
  add column hba1c_percent numeric(3,1),
  add column teeth_lost_to_periodontitis smallint,
  add column radiographic_bone_loss_percent smallint;

alter table public.periodontal_examinations
  add constraint perio_exam_age_snapshot_range
    check (age_years_snapshot is null or age_years_snapshot between 0 and 130),
  add constraint perio_exam_smoking_status_check
    check (smoking_status is null or smoking_status in ('NEVER', 'FORMER', 'CURRENT')),
  add constraint perio_exam_cigarettes_range
    check (cigarettes_per_day is null or cigarettes_per_day between 0 and 100),
  -- Cigarettes per day is the 2018 grade modifier for a current smoker. On a
  -- never or former smoker it describes nothing.
  add constraint perio_exam_cigarettes_current_smoker_check
    check (cigarettes_per_day is null or smoking_status = 'CURRENT'),
  add constraint perio_exam_diabetes_status_check
    check (diabetes_status is null or diabetes_status in ('NONE', 'TYPE_1', 'TYPE_2', 'OTHER')),
  add constraint perio_exam_hba1c_range
    check (hba1c_percent is null or hba1c_percent between 3.0 and 20.0),
  add constraint perio_exam_teeth_lost_range
    check (teeth_lost_to_periodontitis is null or teeth_lost_to_periodontitis between 0 and 32),
  add constraint perio_exam_bone_loss_range
    check (radiographic_bone_loss_percent is null or radiographic_bone_loss_percent between 0 and 100);

comment on column public.periodontal_examinations.age_years_snapshot is
  'Patient age in whole years at the examination, 0-130. Snapshotted so a later birthday cannot silently regrade a finalized examination. NULL when not captured.';
comment on column public.periodontal_examinations.smoking_status is
  'NEVER, FORMER, or CURRENT. NULL means not recorded; there is deliberately no UNKNOWN sentinel because NULL already carries it.';
comment on column public.periodontal_examinations.cigarettes_per_day is
  'Cigarettes per day 0-100, accepted only when smoking_status is CURRENT. NULL when not recorded.';
comment on column public.periodontal_examinations.diabetes_status is
  'NONE, TYPE_1, TYPE_2, or OTHER. NULL when not recorded.';
comment on column public.periodontal_examinations.hba1c_percent is
  'Glycated haemoglobin as a percentage, 3.0-20.0. NULL when not recorded.';
comment on column public.periodontal_examinations.teeth_lost_to_periodontitis is
  'Teeth lost to periodontitis, 0-32. NULL when not recorded. Distinct from teeth lost to caries or trauma.';
comment on column public.periodontal_examinations.radiographic_bone_loss_percent is
  'Radiographic bone loss at the worst-affected site as a percentage of root length, 0-100. NULL when no radiograph was assessed.';

-- ---------------------------------------------------------------------------
-- 5. Derived and clinician-confirmed classification
-- ---------------------------------------------------------------------------

alter table public.periodontal_examinations
  add column derived_diagnosis text,
  add column derived_stage text,
  add column derived_grade text,
  add column derived_extent text,
  add column derived_measurement_fingerprint text,
  add column confirmed_diagnosis text,
  add column confirmed_stage text,
  add column confirmed_grade text,
  add column confirmed_extent text,
  add column confirmed_measurement_fingerprint text,
  add column confirmed_at timestamptz,
  add column confirmed_by uuid references auth.users(id) on delete set null,
  add column confirmed_provider_id uuid,
  add column classification_override_reason text,
  add column amendment_reason text;

-- A confirming clinician must belong to the examination's own organization.
alter table public.periodontal_examinations
  add constraint perio_exam_organization_confirmed_provider_fk
  foreign key (organization_id, confirmed_provider_id)
  references public.providers (organization_id, id)
  on delete restrict;

alter table public.periodontal_examinations
  add constraint perio_exam_derived_diagnosis_check check (
    derived_diagnosis is null or derived_diagnosis in (
      'HEALTH', 'GINGIVITIS', 'PERIODONTITIS', 'NECROTIZING_PERIODONTAL_DISEASE',
      'PERIODONTITIS_AS_MANIFESTATION_OF_SYSTEMIC_DISEASE',
      'PERI_IMPLANT_HEALTH', 'PERI_IMPLANT_MUCOSITIS', 'PERI_IMPLANTITIS'
    )
  ),
  add constraint perio_exam_confirmed_diagnosis_check check (
    confirmed_diagnosis is null or confirmed_diagnosis in (
      'HEALTH', 'GINGIVITIS', 'PERIODONTITIS', 'NECROTIZING_PERIODONTAL_DISEASE',
      'PERIODONTITIS_AS_MANIFESTATION_OF_SYSTEMIC_DISEASE',
      'PERI_IMPLANT_HEALTH', 'PERI_IMPLANT_MUCOSITIS', 'PERI_IMPLANTITIS'
    )
  ),
  add constraint perio_exam_derived_stage_check
    check (derived_stage is null or derived_stage in ('I', 'II', 'III', 'IV')),
  add constraint perio_exam_derived_grade_check
    check (derived_grade is null or derived_grade in ('A', 'B', 'C')),
  add constraint perio_exam_derived_extent_check
    check (derived_extent is null or derived_extent in ('LOCALIZED', 'GENERALIZED', 'MOLAR_INCISOR')),
  add constraint perio_exam_confirmed_stage_check
    check (confirmed_stage is null or confirmed_stage in ('I', 'II', 'III', 'IV')),
  add constraint perio_exam_confirmed_grade_check
    check (confirmed_grade is null or confirmed_grade in ('A', 'B', 'C')),
  add constraint perio_exam_confirmed_extent_check
    check (confirmed_extent is null or confirmed_extent in ('LOCALIZED', 'GENERALIZED', 'MOLAR_INCISOR')),
  add constraint perio_exam_derived_fingerprint_check
    check (derived_measurement_fingerprint is null or derived_measurement_fingerprint ~ '^[0-9a-f]{64}$'),
  add constraint perio_exam_confirmed_fingerprint_check
    check (confirmed_measurement_fingerprint is null or confirmed_measurement_fingerprint ~ '^[0-9a-f]{64}$'),
  -- A derived classification without the measurements it came from is not
  -- provenance, and a stage without a diagnosis is not a classification.
  add constraint perio_exam_derived_complete_check check (
    (derived_diagnosis is not null) = (derived_measurement_fingerprint is not null)
    and (
      derived_diagnosis is not null
      or (derived_stage is null and derived_grade is null and derived_extent is null)
    )
  ),
  add constraint perio_exam_confirmed_complete_check check (
    (confirmed_at is not null) = (confirmed_by is not null)
    and (confirmed_at is not null) = (confirmed_provider_id is not null)
    and (confirmed_at is not null) = (confirmed_diagnosis is not null)
    and (confirmed_at is not null) = (confirmed_measurement_fingerprint is not null)
    and (
      confirmed_diagnosis is not null
      or (confirmed_stage is null and confirmed_grade is null and confirmed_extent is null)
    )
  ),
  -- Health, gingivitis, peri-implant health, and peri-implant mucositis are
  -- never staged or graded.
  add constraint perio_exam_derived_stageable_check check (
    derived_diagnosis is null
    or derived_diagnosis not in ('HEALTH', 'GINGIVITIS', 'PERI_IMPLANT_HEALTH', 'PERI_IMPLANT_MUCOSITIS')
    or (derived_stage is null and derived_grade is null and derived_extent is null)
  ),
  add constraint perio_exam_confirmed_stageable_check check (
    confirmed_diagnosis is null
    or confirmed_diagnosis not in ('HEALTH', 'GINGIVITIS', 'PERI_IMPLANT_HEALTH', 'PERI_IMPLANT_MUCOSITIS')
    or (confirmed_stage is null and confirmed_grade is null and confirmed_extent is null)
  ),
  add constraint perio_exam_override_reason_bounded_check check (
    classification_override_reason is null
    or (pg_catalog.btrim(classification_override_reason) <> ''
        and pg_catalog.length(classification_override_reason) <= 2000)
  ),
  add constraint perio_exam_override_reason_scope_check
    check (classification_override_reason is null or confirmed_at is not null),
  -- Departing from the derived classification is a clinical judgement. It is
  -- recorded with its reason or it is not recorded at all.
  add constraint perio_exam_override_reason_required_check check (
    confirmed_at is null
    or (confirmed_diagnosis is not distinct from derived_diagnosis
        and confirmed_stage is not distinct from derived_stage
        and confirmed_grade is not distinct from derived_grade
        and confirmed_extent is not distinct from derived_extent)
    or classification_override_reason is not null
  ),
  add constraint perio_exam_amendment_reason_bounded_check check (
    amendment_reason is null
    or (pg_catalog.btrim(amendment_reason) <> ''
        and pg_catalog.length(amendment_reason) <= 2000)
  ),
  add constraint perio_exam_amendment_reason_scope_check
    check (amendment_reason is null or predecessor_examination_id is not null),
  -- A DRAFT amendment may be autosaved while the clinician works. The FINAL
  -- record that actually supersedes finalized clinical history may not exist
  -- without saying why.
  add constraint perio_exam_final_amendment_reason_check check (
    status <> 'FINAL'
    or predecessor_examination_id is null
    or amendment_reason is not null
  );

comment on column public.periodontal_examinations.derived_diagnosis is
  'Classification computed from the canonical measurements. Never overwritten by the clinician-confirmed value.';
comment on column public.periodontal_examinations.derived_measurement_fingerprint is
  'SHA-256 hex digest of the canonical measurements the derived classification was computed from, produced by private.periodontal_measurement_digest. A constraint trigger refuses any value that is not the true digest at write time.';
comment on column public.periodontal_examinations.confirmed_diagnosis is
  'Classification the treating clinician stands behind. Stored separately from the derived value so a disagreement is visible rather than lost.';
comment on column public.periodontal_examinations.confirmed_measurement_fingerprint is
  'SHA-256 hex digest of the canonical measurements as they stood when the clinician confirmed. Recomputing the digest later reveals a confirmation that no longer matches its evidence.';
comment on column public.periodontal_examinations.confirmed_provider_id is
  'The confirming clinician, constrained to the examination''s own organization by a composite tenant-safe foreign key. Derived server-side from the signed-in user; never accepted from a client.';
comment on column public.periodontal_examinations.classification_override_reason is
  'Why the confirmed classification departs from the derived one. Mandatory whenever they differ, bounded to 2000 characters, non-empty, and never copied into an audit event.';
comment on column public.periodontal_examinations.amendment_reason is
  'Why this examination supersedes its predecessor. Accepted only with a predecessor and mandatory once the amendment is FINAL. The predecessor row is never mutated.';

-- ---------------------------------------------------------------------------
-- 6. Amendment lineage and read indexes
-- ---------------------------------------------------------------------------

-- The non-forking supersession chain is ALREADY enforced: 20260828020508
-- created the partial unique index periodontal_examinations_one_amendment_idx
-- on (organization_id, predecessor_examination_id) where the predecessor is not
-- null. No second index is created here; a duplicate would cost every write and
-- guarantee nothing extra. The suite asserts the existing index by name so the
-- guarantee cannot be dropped silently by a later migration.

-- The workspace loads the examination for the visit it is standing in.
create index perio_exam_org_encounter_idx
  on public.periodontal_examinations (organization_id, encounter_id);

-- Resuming the open draft for a patient.
create index perio_exam_org_patient_draft_idx
  on public.periodontal_examinations (organization_id, patient_id, recorded_at desc)
  where status = 'DRAFT';

-- ---------------------------------------------------------------------------
-- 7. The canonical measurement digest
-- ---------------------------------------------------------------------------

-- One authoritative definition of "the measurements of this examination", so a
-- fingerprint written by any path means the same thing. The aggregate order is
-- pinned to the C collation so a locale change can never silently reorder the
-- input and invalidate every stored fingerprint.
-- Null-bearing columns are rendered as '~' rather than skipped, because a
-- digest that cannot tell (3, null, 2) from (3, 2) is not a digest.
create function private.periodontal_measurement_digest(
  p_organization_id uuid,
  p_examination_id uuid
)
returns text
language sql
stable
set search_path = ''
as $$
  select pg_catalog.encode(
    pg_catalog.sha256(
      pg_catalog.convert_to(
        coalesce((
          select pg_catalog.string_agg(
            site.tooth_fdi || ':' || site.site || ':'
              || coalesce(site.probing_depth_mm::text, '~') || ':'
              || coalesce(site.gingival_margin_mm::text, '~') || ':'
              || coalesce(site.bleeding_on_probing::text, '~') || ':'
              || coalesce(site.suppuration::text, '~') || ':'
              || coalesce(site.tooth_present::text, '~') || ':'
              || coalesce(site.implant_context::text, '~'),
            ';' order by site.tooth_fdi collate "C", site.site collate "C")
          from public.periodontal_site_measurements as site
          where site.organization_id = p_organization_id
            and site.examination_id = p_examination_id
        ), '') || '|' ||
        coalesce((
          select pg_catalog.string_agg(
            surface.tooth_fdi || ':' || surface.surface || ':'
              || coalesce(surface.plaque_present::text, '~') || ':'
              || coalesce(surface.plaque_index::text, '~') || ':'
              || coalesce(surface.gingival_index::text, '~') || ':'
              || coalesce(surface.modified_plaque_index::text, '~') || ':'
              || coalesce(surface.modified_bleeding_index::text, '~'),
            ';' order by surface.tooth_fdi collate "C", surface.surface collate "C")
          from public.periodontal_plaque_measurements as surface
          where surface.organization_id = p_organization_id
            and surface.examination_id = p_examination_id
        ), '') || '|' ||
        coalesce((
          select pg_catalog.string_agg(
            tooth.tooth_fdi || ':'
              || coalesce(tooth.mobility_miller, '~') || ':'
              || coalesce(tooth.tooth_present::text, '~') || ':'
              || coalesce(tooth.implant_context::text, '~') || ':'
              || coalesce(tooth.keratinized_gingiva_mm::text, '~') || ':'
              || coalesce(tooth.gingival_thickness_mm::text, '~') || ':'
              || coalesce(tooth.gingival_phenotype, '~') || ':'
              || coalesce(tooth.miller_recession_class, '~') || ':'
              || coalesce(tooth.cej_visible::text, '~') || ':'
              || coalesce(tooth.root_concavity::text, '~'),
            ';' order by tooth.tooth_fdi collate "C")
          from public.periodontal_tooth_measurements as tooth
          where tooth.organization_id = p_organization_id
            and tooth.examination_id = p_examination_id
        ), '') || '|' ||
        coalesce((
          select pg_catalog.string_agg(
            furcation.tooth_fdi || ':' || furcation.entrance || ':'
              || coalesce(furcation.grade::text, '~'),
            ';' order by furcation.tooth_fdi collate "C", furcation.entrance collate "C")
          from public.periodontal_furcation_measurements as furcation
          where furcation.organization_id = p_organization_id
            and furcation.examination_id = p_examination_id
        ), ''),
        'UTF8'
      )
    ),
    'hex'
  );
$$;

revoke all on function private.periodontal_measurement_digest(uuid, uuid)
from public, anon, authenticated, service_role;

comment on function private.periodontal_measurement_digest(uuid, uuid) is
  'Deterministic SHA-256 hex digest over the canonical site, surface, tooth, and furcation measurements of one periodontal examination in one organization. The single definition of what a classification fingerprint covers. Not browser or service callable.';

-- ---------------------------------------------------------------------------
-- 8. Classification fingerprints cannot be forged
-- ---------------------------------------------------------------------------

-- AFTER, so the column domain and completeness checks report first and this
-- trigger only speaks about a value that is otherwise well formed. It fires
-- only when a fingerprint column actually changes, so an ordinary later edit to
-- the row does not have to re-derive anything.
create function private.enforce_perio_classification_fingerprint()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_digest text;
begin
  if new.derived_measurement_fingerprint is not null
     and (tg_op = 'INSERT'
          or new.derived_measurement_fingerprint is distinct from old.derived_measurement_fingerprint) then
    v_digest := private.periodontal_measurement_digest(new.organization_id, new.id);
    if new.derived_measurement_fingerprint <> v_digest then
      raise check_violation using
        message = 'derived measurement fingerprint does not match the examination measurements';
    end if;
  end if;

  if new.confirmed_measurement_fingerprint is not null
     and (tg_op = 'INSERT'
          or new.confirmed_measurement_fingerprint is distinct from old.confirmed_measurement_fingerprint) then
    v_digest := private.periodontal_measurement_digest(new.organization_id, new.id);
    if new.confirmed_measurement_fingerprint <> v_digest then
      raise check_violation using
        message = 'confirmed measurement fingerprint does not match the examination measurements';
    end if;
  end if;

  return new;
end
$$;

revoke all on function private.enforce_perio_classification_fingerprint()
from public, anon, authenticated, service_role;

comment on function private.enforce_perio_classification_fingerprint() is
  'Refuses a derived or confirmed measurement fingerprint that is not the true private.periodontal_measurement_digest of the examination at write time, so classification provenance cannot be forged or back-dated. Runs only when a fingerprint column changes.';

create constraint trigger perio_exam_verify_classification_fingerprint
after insert or update on public.periodontal_examinations
deferrable initially immediate
for each row execute function private.enforce_perio_classification_fingerprint();

-- ---------------------------------------------------------------------------
-- 9. Surface index applicability against the authoritative implant context
-- ---------------------------------------------------------------------------

-- Enforced from BOTH sides. Checking only the surface row would leave the
-- inverse hole open: score a natural tooth, then flip the tooth to an implant,
-- and the examination is left carrying Silness-Loe scores on a peri-implant
-- sulcus with nothing to notice.
create function private.validate_perio_surface_index_context()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_implant boolean;
begin
  if tg_table_name = 'periodontal_tooth_measurements' then
    if new.implant_context then
      if exists (
        select 1
        from public.periodontal_plaque_measurements as surface
        where surface.organization_id = new.organization_id
          and surface.examination_id = new.examination_id
          and surface.tooth_fdi = new.tooth_fdi
          and (surface.plaque_index is not null or surface.gingival_index is not null)
      ) then
        raise check_violation using
          message = 'peri-implant surfaces use the modified plaque and bleeding indices';
      end if;
    else
      if exists (
        select 1
        from public.periodontal_plaque_measurements as surface
        where surface.organization_id = new.organization_id
          and surface.examination_id = new.examination_id
          and surface.tooth_fdi = new.tooth_fdi
          and (surface.modified_plaque_index is not null
               or surface.modified_bleeding_index is not null)
      ) then
        raise check_violation using
          message = 'modified plaque and bleeding indices apply only to peri-implant surfaces';
      end if;
    end if;

    return new;
  end if;

  select tooth.implant_context into v_implant
  from public.periodontal_tooth_measurements as tooth
  where tooth.organization_id = new.organization_id
    and tooth.examination_id = new.examination_id
    and tooth.tooth_fdi = new.tooth_fdi;

  if coalesce(v_implant, false) then
    if new.plaque_index is not null or new.gingival_index is not null then
      raise check_violation using
        message = 'peri-implant surfaces use the modified plaque and bleeding indices';
    end if;
  else
    if new.modified_plaque_index is not null or new.modified_bleeding_index is not null then
      raise check_violation using
        message = 'modified plaque and bleeding indices apply only to peri-implant surfaces';
    end if;
  end if;

  return new;
end
$$;

revoke all on function private.validate_perio_surface_index_context()
from public, anon, authenticated, service_role;

comment on function private.validate_perio_surface_index_context() is
  'Refuses the Silness-Loe / Loe-Silness index family on a peri-implant surface and the Mombelli modified family on a natural-tooth surface. It reads the implant context from the tooth row rather than trusting a duplicated flag on the surface row, and runs on both tables so neither writing order can leave a surface scored with the wrong family.';

create constraint trigger perio_plaque_surface_index_context_check
after insert or update on public.periodontal_plaque_measurements
deferrable initially immediate
for each row execute function private.validate_perio_surface_index_context();

create constraint trigger perio_tooth_surface_index_context_check
after insert or update on public.periodontal_tooth_measurements
deferrable initially immediate
for each row execute function private.validate_perio_surface_index_context();

-- ---------------------------------------------------------------------------
-- 10. The inferred-context merge must carry the new tooth properties
-- ---------------------------------------------------------------------------

-- private.enforce_periodontal_tooth_context creates a placeholder tooth row
-- when a site, surface, or furcation row arrives first, then merges the real
-- tooth row into it. That merge lists its columns explicitly, so without this
-- repair every property added above would be silently dropped whenever the
-- children happened to be written first. 20260828020520 is applied and is not
-- edited; the guarded-replace pattern verifies the target occurs exactly once
-- and fails closed with 55000.
do $migration$
declare
  v_definition text;
  v_repaired text;
  v_target text := $target$        update public.periodontal_tooth_measurements
        set tooth_present = new.tooth_present,
            mobility_miller = new.mobility_miller,
            implant_context = new.implant_context,
            context_inferred = false$target$;
  v_replacement text := $replacement$        update public.periodontal_tooth_measurements
        set tooth_present = new.tooth_present,
            mobility_miller = new.mobility_miller,
            implant_context = new.implant_context,
            notes = new.notes,
            keratinized_gingiva_mm = new.keratinized_gingiva_mm,
            gingival_thickness_mm = new.gingival_thickness_mm,
            gingival_phenotype = new.gingival_phenotype,
            miller_recession_class = new.miller_recession_class,
            cej_visible = new.cej_visible,
            root_concavity = new.root_concavity,
            context_inferred = false$replacement$;
begin
  -- The stored body carries whatever newline convention its source migration
  -- had on the machine that applied it, and THIS file is checked out with the
  -- convention of the machine replaying it. Both sides are normalized to LF so
  -- a multi-line anchor cannot silently fail on a CRLF checkout. Matching is
  -- exact substring counting, never a regex: an unescaped metacharacter in a
  -- SQL anchor would make the count meaningless.
  v_target := pg_catalog.replace(v_target, pg_catalog.chr(13) || pg_catalog.chr(10), pg_catalog.chr(10));
  v_replacement := pg_catalog.replace(v_replacement, pg_catalog.chr(13) || pg_catalog.chr(10), pg_catalog.chr(10));

  select pg_catalog.replace(
    pg_catalog.pg_get_functiondef('private.enforce_periodontal_tooth_context()'::regprocedure),
    pg_catalog.chr(13) || pg_catalog.chr(10),
    pg_catalog.chr(10)
  ) into v_definition;

  if (pg_catalog.length(v_definition)
      - pg_catalog.length(pg_catalog.replace(v_definition, v_target, '')))
     / pg_catalog.length(v_target) <> 1 then
    raise exception using errcode = '55000',
      message = 'enforce_periodontal_tooth_context inferred-merge update not found exactly once';
  end if;

  v_repaired := pg_catalog.replace(v_definition, v_target, v_replacement);

  if v_repaired = v_definition then
    raise exception using errcode = '55000',
      message = 'enforce_periodontal_tooth_context inferred-merge replacement made no change';
  end if;

  execute v_repaired;
end
$migration$;

-- ---------------------------------------------------------------------------
-- 11. An amendment clone must carry the expanded record
-- ---------------------------------------------------------------------------

-- public.amend_periodontal_examination clones the predecessor into the new
-- DRAFT with explicit column lists. Extending the tables without extending
-- those lists would make an amendment quietly discard every measurement added
-- above, which is exactly the silent overwrite the amendment path exists to
-- prevent. Three guarded replaces, each verified to occur exactly once.
--
-- The examination-level risk inputs are cloned because an amendment corrects
-- the same examination event and the patient's risk snapshot at that visit is
-- unchanged. The classification block is deliberately NOT cloned: a corrected
-- measurement set must be re-derived and re-confirmed, and the fingerprint of
-- the predecessor would not match the successor's measurements.
do $migration$
declare
  v_definition text;
  v_repaired text;
  v_step text;

  v_exam_target text := $target$    organization_id, patient_id, encounter_id, predecessor_examination_id,
    examination_kind, status, version, examined_at, examined_by, examined_provider_id
  ) values (
    v_organization_id, v_pred.patient_id, p_encounter_id, p_predecessor_examination_id,
    'AMENDMENT', 'DRAFT', v_pred.version + 1,
    pg_catalog.statement_timestamp(), v_actor_user_id, coalesce(v_provider_id, v_pred.examined_provider_id)
  )$target$;
  v_exam_replacement text := $replacement$    organization_id, patient_id, encounter_id, predecessor_examination_id,
    examination_kind, status, version, examined_at, examined_by, examined_provider_id,
    age_years_snapshot, smoking_status, cigarettes_per_day, diabetes_status,
    hba1c_percent, teeth_lost_to_periodontitis, radiographic_bone_loss_percent
  ) values (
    v_organization_id, v_pred.patient_id, p_encounter_id, p_predecessor_examination_id,
    'AMENDMENT', 'DRAFT', v_pred.version + 1,
    pg_catalog.statement_timestamp(), v_actor_user_id, coalesce(v_provider_id, v_pred.examined_provider_id),
    v_pred.age_years_snapshot, v_pred.smoking_status, v_pred.cigarettes_per_day, v_pred.diabetes_status,
    v_pred.hba1c_percent, v_pred.teeth_lost_to_periodontitis, v_pred.radiographic_bone_loss_percent
  )$replacement$;

  v_plaque_target text := $target$  insert into public.periodontal_plaque_measurements (
    organization_id, examination_id, tooth_fdi, surface, plaque_present
  )
  select v_organization_id, v_new_id, m.tooth_fdi, m.surface, m.plaque_present$target$;
  v_plaque_replacement text := $replacement$  insert into public.periodontal_plaque_measurements (
    organization_id, examination_id, tooth_fdi, surface, plaque_present,
    plaque_index, gingival_index, modified_plaque_index, modified_bleeding_index
  )
  select v_organization_id, v_new_id, m.tooth_fdi, m.surface, m.plaque_present,
         m.plaque_index, m.gingival_index, m.modified_plaque_index, m.modified_bleeding_index$replacement$;

  v_tooth_target text := $target$  insert into public.periodontal_tooth_measurements (
    organization_id, examination_id, tooth_fdi, mobility_miller, implant_context
  )
  select v_organization_id, v_new_id, m.tooth_fdi, m.mobility_miller, m.implant_context$target$;
  v_tooth_replacement text := $replacement$  insert into public.periodontal_tooth_measurements (
    organization_id, examination_id, tooth_fdi, mobility_miller, implant_context,
    tooth_present, notes, keratinized_gingiva_mm, gingival_thickness_mm,
    gingival_phenotype, miller_recession_class, cej_visible, root_concavity
  )
  select v_organization_id, v_new_id, m.tooth_fdi, m.mobility_miller, m.implant_context,
         m.tooth_present, m.notes, m.keratinized_gingiva_mm, m.gingival_thickness_mm,
         m.gingival_phenotype, m.miller_recession_class, m.cej_visible, m.root_concavity$replacement$;
  v_target text;
  v_replacement text;
begin
  -- Normalized for the same reason as the repair above: 20260828020400 is a
  -- CRLF file, so its stored body carries CR characters that no LF anchor
  -- written here would ever match. Re-creating from the normalized text also
  -- leaves one stable convention behind for the next forward migration.
  select pg_catalog.replace(
    pg_catalog.pg_get_functiondef('public.amend_periodontal_examination(uuid,uuid,uuid)'::regprocedure),
    pg_catalog.chr(13) || pg_catalog.chr(10),
    pg_catalog.chr(10)
  ) into v_repaired;

  foreach v_step in array array['exam', 'plaque', 'tooth'] loop
    v_definition := v_repaired;
    v_target := case v_step
      when 'exam' then v_exam_target
      when 'plaque' then v_plaque_target
      else v_tooth_target
    end;
    v_replacement := case v_step
      when 'exam' then v_exam_replacement
      when 'plaque' then v_plaque_replacement
      else v_tooth_replacement
    end;
    -- Both sides normalized to LF: this file is checked out with the newline
    -- convention of whatever machine replays it.
    v_target := pg_catalog.replace(v_target, pg_catalog.chr(13) || pg_catalog.chr(10), pg_catalog.chr(10));
    v_replacement := pg_catalog.replace(v_replacement, pg_catalog.chr(13) || pg_catalog.chr(10), pg_catalog.chr(10));

    if (pg_catalog.length(v_definition)
        - pg_catalog.length(pg_catalog.replace(v_definition, v_target, '')))
       / pg_catalog.length(v_target) <> 1 then
      raise exception using errcode = '55000',
        message = 'amend_periodontal_examination ' || v_step || ' clone target not found exactly once';
    end if;

    v_repaired := pg_catalog.replace(v_definition, v_target, v_replacement);

    if v_repaired = v_definition then
      raise exception using errcode = '55000',
        message = 'amend_periodontal_examination ' || v_step || ' clone replacement made no change';
    end if;
  end loop;

  execute v_repaired;
end
$migration$;

comment on function public.amend_periodontal_examination(uuid, uuid, uuid) is
  'Creates a DRAFT AMENDMENT of a FINAL periodontal examination under patient.clinical.write plus patient.clinical.correct, deriving organization, actor, and provider server-side. It clones the predecessor''s full expanded measurement set and its examination-level risk snapshot, never the classification block, and never mutates the predecessor. The amendment reason is written by the periodontal workspace boundary before the amendment is finalized; a FINAL amendment without one is refused by perio_exam_final_amendment_reason_check.';
