import "server-only";
import sharp from "sharp";
import { createHash } from "node:crypto";
import { createStorageClient } from "@/lib/storage";
import { PHOTO_VARIANTS } from "./types";
const MAX_BYTES=25*1024*1024; const MAX_DIMENSION=12000;
type ProcessorDeps={storage?:ReturnType<typeof createStorageClient>};
async function bytes(stream:ReadableStream<Uint8Array>){return new Uint8Array(await new Response(stream).arrayBuffer());}
function detectedMime(b:Uint8Array){if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return "image/jpeg";if(b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47)return "image/png";if(String.fromCharCode(...b.slice(0,4))==="RIFF"&&String.fromCharCode(...b.slice(8,12))==="WEBP")return "image/webp";return null;}
export async function processClinicalPhoto(input:{photoId:string;sourceObjectKey:string;organizationId:string;patientId:string},deps:ProcessorDeps={}){const storage=deps.storage??createStorageClient(); const expectedSourcePrefix=`org/${input.organizationId}/patients/${input.patientId}/files/`; if(!input.sourceObjectKey.startsWith(expectedSourcePrefix)||!/^org\/[0-9a-f-]+\/patients\/[0-9a-f-]+\/files\/[0-9a-f-]+$/i.test(input.sourceObjectKey))throw new Error("PHOTO_SOURCE_INVALID"); const sourceStat=await storage.stat(input.sourceObjectKey); if(sourceStat.sizeBytes===0||sourceStat.sizeBytes>MAX_BYTES)throw new Error("PHOTO_SIZE_INVALID"); const original=await storage.get(input.sourceObjectKey); if(original.contentType!==sourceStat.contentType)throw new Error("PHOTO_TYPE_INVALID"); const source=await bytes(original.body); if(source.byteLength===0||source.byteLength>MAX_BYTES||source.byteLength!==sourceStat.sizeBytes)throw new Error("PHOTO_SIZE_INVALID"); const mime=detectedMime(source); if(!mime||mime!==original.contentType)throw new Error("PHOTO_TYPE_INVALID"); const image=sharp(source,{failOn:"error"}); const metadata=await image.metadata(); if(!metadata.width||!metadata.height||metadata.width>MAX_DIMENSION||metadata.height>MAX_DIMENSION)throw new Error("PHOTO_DIMENSIONS_INVALID"); const checksum=createHash("sha256").update(source).digest("hex"); const results=[]; for(const variant of Object.keys(PHOTO_VARIANTS)){const spec=PHOTO_VARIANTS[variant as keyof typeof PHOTO_VARIANTS]; const out=await image.clone().rotate().resize({width:spec.width,height:spec.height,fit:spec.fit}).jpeg({quality:85}).toBuffer(); const objectKey=`org/${input.organizationId}/patients/${input.patientId}/clinical-photos/${input.photoId}/${variant}.jpg`; const saved=await storage.put(objectKey,new Response(out).body!,"image/jpeg"); const derivativeMetadata=await sharp(out).metadata(); results.push({variant,objectKey,mimeType:"image/jpeg",sizeBytes:out.byteLength,width:derivativeMetadata.width ?? 0,height:derivativeMetadata.height ?? 0,checksumSha256:saved.checksum});} return {sourceChecksumSha256:checksum,sourceSizeBytes:source.byteLength,derivatives:results};}
