import "server-only";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { clinicalPhotoRowSchema, createClinicalPhotoInputSchema, listClinicalPhotosInputSchema, pairClinicalPhotoInputSchema, recordClinicalPhotoDerivativesInputSchema, renameClinicalPhotoInputSchema } from "./schema";
import type { ClinicalPhotoDTO } from "./types";
const rpcResponse=z.object({data:z.unknown(),error:z.unknown().nullable()});
async function rpc(name:string,args:Record<string,unknown>){const client=await createClient();const response=rpcResponse.parse(await (client.rpc as unknown as (n:string,a:Record<string,unknown>)=>Promise<unknown>)(name,args));if(response.error)throw new Error("PHOTO_NOT_AUTHORIZED");return response.data;}
function map(row:z.infer<typeof clinicalPhotoRowSchema>):ClinicalPhotoDTO{return {photoId:row.photo_id,patientId:row.patient_id,procedureCaseId:row.procedure_case_id,category:row.category,displayFilename:row.display_filename,captureAt:row.capture_at,toothCodes:row.tooth_codes,surfaces:row.surfaces,note:row.note,processingStatus:row.processing_status,pairedPhotoId:row.paired_photo_id,version:row.version};}
export async function createClinicalPhoto(input:unknown){const v=createClinicalPhotoInputSchema.parse(input);const rows=await rpc("create_clinical_photo",{p_acting_branch_id:v.actingBranchId,p_patient_id:v.patientId,p_source_file_id:v.sourceFileId,p_procedure_case_id:v.procedureCaseId,p_category:v.category,p_display_filename:v.displayFilename,p_original_client_filename:v.originalClientFilename,p_capture_at:v.captureAt,p_tooth_codes:v.toothCodes,p_surfaces:v.surfaces,p_note:v.note});return map(clinicalPhotoRowSchema.parse(Array.isArray(rows)?rows[0]:rows));}
export async function listClinicalPhotos(input:unknown){const v=listClinicalPhotosInputSchema.parse(input);const rows=await rpc("list_clinical_photos",{p_acting_branch_id:v.actingBranchId,p_patient_id:v.patientId});return z.array(clinicalPhotoRowSchema).parse(rows).map(map);}
export async function renameClinicalPhoto(input:unknown){const v=renameClinicalPhotoInputSchema.parse(input);const rows=await rpc("rename_clinical_photo",{p_acting_branch_id:v.actingBranchId,p_photo_id:v.photoId,p_expected_version:v.expectedVersion,p_display_filename:v.displayFilename});return map(clinicalPhotoRowSchema.parse(Array.isArray(rows)?rows[0]:rows));}
export async function pairClinicalPhotos(input:unknown){const v=pairClinicalPhotoInputSchema.parse(input);await rpc("pair_clinical_photos",{p_acting_branch_id:v.actingBranchId,p_before_photo_id:v.beforePhotoId,p_after_photo_id:v.afterPhotoId});}
export async function recordClinicalPhotoDerivatives(input:unknown){const v=recordClinicalPhotoDerivativesInputSchema.parse(input);await rpc("record_clinical_photo_derivatives",{p_acting_branch_id:v.actingBranchId,p_photo_id:v.photoId,p_source_checksum_sha256:v.sourceChecksumSha256,p_source_size_bytes:v.sourceSizeBytes,p_derivatives:v.derivatives.map((d)=>({variant:d.variant,object_key:d.objectKey,mime_type:d.mimeType,width:d.width,height:d.height,size_bytes:d.sizeBytes,checksum_sha256:d.checksumSha256}))});}
